/*
 * Radix Core API
 *
 * This API is exposed by the Babylon Radix node to give clients access to the Radix Engine, Mempool and State in the node.  The default configuration is intended for use by node-runners on a private network, and is not intended to be exposed publicly. Very heavy load may impact the node's function. The node exposes a configuration flag which allows disabling certain endpoints which may be problematic, but monitoring is advised. This configuration parameter is `api.core.flags.enable_unbounded_endpoints` / `RADIXDLT_CORE_API_FLAGS_ENABLE_UNBOUNDED_ENDPOINTS`.  This API exposes queries against the node's current state (see `/lts/state/` or `/state/`), and streams of transaction history (under `/lts/stream/` or `/stream`).  If you require queries against snapshots of historical ledger state, you may also wish to consider using the [Gateway API](https://docs-babylon.radixdlt.com/).  ## Integration and forward compatibility guarantees  Integrators (such as exchanges) are recommended to use the `/lts/` endpoints - they have been designed to be clear and simple for integrators wishing to create and monitor transactions involving fungible transfers to/from accounts.  All endpoints under `/lts/` have high guarantees of forward compatibility in future node versions. We may add new fields, but existing fields will not be changed. Assuming the integrating code uses a permissive JSON parser which ignores unknown fields, any additions will not affect existing code.  Other endpoints may be changed with new node versions carrying protocol-updates, although any breaking changes will be flagged clearly in the corresponding release notes.  All responses may have additional fields added, so clients are advised to use JSON parsers which ignore unknown fields on JSON objects. 
 *
 * The version of the OpenAPI document: v1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "substate_type")]
pub enum Substate {
    #[serde(rename="AccessControllerFieldState")]
    AccessControllerFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="AccountAuthorizedDepositorEntry")]
    AccountAuthorizedDepositorEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="AccountFieldState")]
    AccountFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="AccountLockerAccountClaimsEntry")]
    AccountLockerAccountClaimsEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="AccountResourcePreferenceEntry")]
    AccountResourcePreferenceEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="AccountVaultEntry")]
    AccountVaultEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="BootLoaderModuleFieldKernelBoot")]
    BootLoaderModuleFieldKernelBootSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="BootLoaderModuleFieldSystemBoot")]
    BootLoaderModuleFieldSystemBootSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="BootLoaderModuleFieldVmBoot")]
    BootLoaderModuleFieldVmBootSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ConsensusManagerFieldConfig")]
    ConsensusManagerFieldConfigSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ConsensusManagerFieldCurrentProposalStatistic")]
    ConsensusManagerFieldCurrentProposalStatisticSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ConsensusManagerFieldCurrentTime")]
    ConsensusManagerFieldCurrentTimeSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ConsensusManagerFieldCurrentTimeRoundedToMinutes")]
    ConsensusManagerFieldCurrentTimeRoundedToMinutesSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ConsensusManagerFieldCurrentValidatorSet")]
    ConsensusManagerFieldCurrentValidatorSetSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ConsensusManagerFieldState")]
    ConsensusManagerFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ConsensusManagerFieldValidatorRewards")]
    ConsensusManagerFieldValidatorRewardsSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ConsensusManagerRegisteredValidatorsByStakeIndexEntry")]
    ConsensusManagerRegisteredValidatorsByStakeIndexEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="FungibleResourceManagerFieldDivisibility")]
    FungibleResourceManagerFieldDivisibilitySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="FungibleResourceManagerFieldTotalSupply")]
    FungibleResourceManagerFieldTotalSupplySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="FungibleVaultFieldBalance")]
    FungibleVaultFieldBalanceSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="FungibleVaultFieldFrozenStatus")]
    FungibleVaultFieldFrozenStatusSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="GenericKeyValueStoreEntry")]
    GenericKeyValueStoreEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="GenericScryptoComponentFieldState")]
    GenericScryptoComponentFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="MetadataModuleEntry")]
    MetadataModuleEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="MultiResourcePoolFieldState")]
    MultiResourcePoolFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="NonFungibleResourceManagerDataEntry")]
    NonFungibleResourceManagerDataEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="NonFungibleResourceManagerFieldIdType")]
    NonFungibleResourceManagerFieldIdTypeSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="NonFungibleResourceManagerFieldMutableFields")]
    NonFungibleResourceManagerFieldMutableFieldsSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="NonFungibleResourceManagerFieldTotalSupply")]
    NonFungibleResourceManagerFieldTotalSupplySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="NonFungibleVaultContentsIndexEntry")]
    NonFungibleVaultContentsIndexEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="NonFungibleVaultFieldBalance")]
    NonFungibleVaultFieldBalanceSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="NonFungibleVaultFieldFrozenStatus")]
    NonFungibleVaultFieldFrozenStatusSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="OneResourcePoolFieldState")]
    OneResourcePoolFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="PackageBlueprintAuthTemplateEntry")]
    PackageBlueprintAuthTemplateEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="PackageBlueprintDefinitionEntry")]
    PackageBlueprintDefinitionEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="PackageBlueprintDependenciesEntry")]
    PackageBlueprintDependenciesEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="PackageBlueprintRoyaltyEntry")]
    PackageBlueprintRoyaltyEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="PackageCodeInstrumentedCodeEntry")]
    PackageCodeInstrumentedCodeEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="PackageCodeOriginalCodeEntry")]
    PackageCodeOriginalCodeEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="PackageCodeVmTypeEntry")]
    PackageCodeVmTypeEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="PackageFieldRoyaltyAccumulator")]
    PackageFieldRoyaltyAccumulatorSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="RoleAssignmentModuleFieldOwnerRole")]
    RoleAssignmentModuleFieldOwnerRoleSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="RoleAssignmentModuleRuleEntry")]
    RoleAssignmentModuleRuleEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="RoyaltyModuleFieldState")]
    RoyaltyModuleFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="RoyaltyModuleMethodRoyaltyEntry")]
    RoyaltyModuleMethodRoyaltyEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="SchemaEntry")]
    SchemaEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="TransactionTrackerCollectionEntry")]
    TransactionTrackerCollectionEntrySubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="TransactionTrackerFieldState")]
    TransactionTrackerFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="TwoResourcePoolFieldState")]
    TwoResourcePoolFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="TypeInfoModuleFieldTypeInfo")]
    TypeInfoModuleFieldTypeInfoSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ValidatorFieldProtocolUpdateReadinessSignal")]
    ValidatorFieldProtocolUpdateReadinessSignalSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
    #[serde(rename="ValidatorFieldState")]
    ValidatorFieldStateSubstate {
        #[serde(rename = "is_locked")]
        is_locked: bool,
    },
}

impl Default for Substate {
    fn default() -> Self {
        Self::AccessControllerFieldStateSubstate {
            is_locked: Default::default(),
        }
        
    }
}


